In [1]:
import torch
import torch.nn as nn


In [2]:
class Model(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        
    def forward(self, features):
        
        out = self.network(features)
        
        return out

In [3]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6009],
        [0.5757],
        [0.5906],
        [0.5714],
        [0.5345],
        [0.5872],
        [0.5819],
        [0.6107],
        [0.5275],
        [0.5497]], grad_fn=<SigmoidBackward0>)

In [4]:
!pip install torchinfo

In [5]:
from torchinfo import summary

summary(model, input_size = (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Datasets and Dataloaders


In [6]:
from sklearn.datasets import make_classification
import torch

In [7]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [8]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [9]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [15]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [16]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [17]:
#main:

from torch.utils.data import Dataset, DataLoader

In [22]:
class CustomDataset(Dataset):
    
    def __init__(self, features, labels):
        
        self.features = features
        self.labels = labels
        
    def __len__(self):
        
        return self.features.shape[0]
    
    def __getitem__(self, index):
        
        return self.features[index], self.labels[index]

In [23]:
dataset = CustomDataset(X, y)

In [24]:
len(dataset)

10

In [25]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [26]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle = False)

In [27]:
for batch_features, batch_labels in dataloader:
    
    print(batch_features)
    print(batch_labels)
    

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
